/* eslint-disable max-len */
import { Metadata } from 'next';

import { config } from '../lib/config';

export const ICONS = [{
  rel: 'icon',
  type: 'image/x-icon',
  sizes: '16x16',
  url: '/images/favicons/favicon.ico',
}, {
  rel: 'icon',
  type: 'image/png',
  sizes: '16x16',
  url: '/images/favicons/favicon-16x16.png',
}, {
  rel: 'icon',
  type: 'image/png',
  sizes: '32x32',
  url: '/images/favicons/favicon-32x32.png',
}, {
  rel: 'icon',
  type: 'image/png',
  sizes: '194x194',
  url: '/images/favicons/favicon-194x194.png',
}, {
  rel: 'apple-touch-icon',
  sizes: '180x180',
  url: '/images/favicons/apple-icon.png',
}, {
  rel: 'mask-icon',
  color: '#ff7c2a',
  url: '/images/favicons/safari-pinned-tab.svg',
}];

export const ES_MAIN_METADATA: Metadata = {
  title: 'Todos los productos | Weestep - be bigger',
  description: 'Descubre una amplia selección de zapatos elegantes y cómodos para niños en Weestep Kids. Nuestra colección incluye zapatillas de moda, sandalias duraderas y botas adorables, todas elaboradas con materiales de calidad. Desde tallas para niños pequeños hasta preadolescentes, encuentra el ajuste perfecto para tu pequeño. Compra calzado infantil asequible y de moda en Weestep Kids y asegúrate de que tu hijo dé cada paso con estilo y comodidad. ¡Explora nuestra gama hoy mismo!',
  metadataBase: new URL(String(config?.urls.site)),
  category: 'Zapatos',
  applicationName: 'Weestep kids',
  alternates: {
    canonical: String(config?.urls.site),
    languages: {
      es: `${config?.urls.site}/es`,
      en: `${config?.urls.site}/en`,
    },
  },
  keywords: [
    'Zapatos para niños',
    'Calzado infantil',
    'Zapatos para bebés',
    'Zapatos lindos y cómodos',
    'Calzado moderno para niños',
    'Zapatos elegantes para niños',
    'Zapatos asequibles para niños',
    'Calzado de alta calidad para niños',
    'Tienda de zapatos para niños en línea',
    'Marcas de calzado infantil',
    'Mejores zapatos para niños',
    'Tallas de zapatos para niños',
    'Zapatos de moda para niños',
    'Venta de zapatos para niños',
    'Tendencias de calzado infantil',
    'Zapatos para niños varones',
    'Zapatos para niñas',
    'Zapatillas para niños',
    'Sandalias para niños',
    'Zapatos escolares para niños',
    'Zapatos deportivos para niños',
    'Zapatos casuales para niños',
    'Accesorios para zapatos infantiles',
    'Zapatos ecológicos para niños',
    'Descuentos en zapatos para niños',
    'Reseñas de zapatos infantiles',
    'Guía de compra de zapatos para niños',
    'Liquidación de zapatos para niños',
    'Tendencias de moda en zapatos para niños',
    'Zapatos ortopédicos para niños',
    'Calzado infantil de soporte',
    'Sandalias ortopédicas para niños',
    'Zapatos con soporte para el arco para niños',
  ],
  icons: ICONS,
  robots: {
    index: false,
    follow: false,
    nosnippet: false,
    notranslate: false,
    noimageindex: false,
    noarchive: false,
    'max-snippet': -1,
    'max-image-preview': 'standard',
    'max-video-preview': -1,
    googleBot: {
      index: false,
      follow: false,
      nosnippet: false,
      notranslate: false,
      noimageindex: false,
      noarchive: false,
      'max-snippet': -1,
      'max-image-preview': 'standard',
      'max-video-preview': -1,
    },
  },
  openGraph: {
    url: config?.urls.site,
    type: 'website',
    title: 'Todos los productos | Weestep - be bigger',
    locale: 'es',
    phoneNumbers: '+34 611-82-25-84',
    siteName: 'Weestep kids',
    alternateLocale: 'en',
    countryName: 'Spain',
    images: {
      url: 'https://img.ankorstore.com/brands/rounded/16969-47df8e2d48b214.jpg?auto=compress&fm=pjpg&h=158&dpr=2',
      width: 200,
      height: 200,
    },
  },
  twitter: {
    site: config?.urls.site,
    title: 'Todos los productos | Weestep - be bigger',
    description: 'Descubre una amplia selección de zapatos elegantes y cómodos para niños en Weestep Kids. Nuestra colección incluye zapatillas de moda, sandalias duraderas y botas adorables, todas elaboradas con materiales de calidad. Desde tallas para niños pequeños hasta preadolescentes, encuentra el ajuste perfecto para tu pequeño. Compra calzado infantil asequible y de moda en Weestep Kids y asegúrate de que tu hijo dé cada paso con estilo y comodidad. ¡Explora nuestra gama hoy mismo!',
    images: {
      url: 'https://img.ankorstore.com/brands/rounded/16969-47df8e2d48b214.jpg?auto=compress&fm=pjpg&h=158&dpr=2',
      width: 200,
      height: 200,
    },
  },
};

export const EN_MAIN_METADATA: Metadata = {
  title: 'All products | Weestep - be bigger',
  description: 'Discover a wide selection of stylish and comfortable kids\' shoes at Weestep Kids. Our collection features trendy sneakers, durable sandals, and adorable boots, all crafted with quality materials. From toddler to pre-teen sizes, find the perfect fit for your little one. Shop affordable and on-trend children\'s footwear at Weestep Kids and ensure your child takes every step in style and comfort. Explore our range today!',
  metadataBase: new URL(String(config?.urls.site)),
  category: 'Shoes',
  applicationName: 'Weestep kids',
  alternates: {
    canonical: String(config?.urls.site),
    languages: {
      es: `${config?.urls.site}/es`,
      en: `${config?.urls.site}/en`,
    },
  },
  keywords: [
    'Kids shoes',
    "Children's footwear",
    'Toddler shoes',
    'Baby shoes',
    'Cute and comfortable shoes',
    "Trendy kids' footwear",
    "Stylish children's shoes",
    'Affordable kids shoes',
    "High-quality children's footwear",
    'Kids shoe store online',
    "Children's shoe brands",
    'Best shoes for kids',
    "Children's shoe sizes",
    'Fashionable kids shoes',
    'Kids shoe sale',
    "Children's shoe trends",
    "Boys' shoes",
    "Girls' shoes",
    'Kids sneakers',
    "Children's sandals",
    'School shoes for kids',
    "Kids' sports shoes",
    'Casual kids shoes',
    "Children's shoe accessories",
    'Eco-friendly kids shoes',
    'Kids shoe discounts',
    "Children's shoe reviews",
    'Kids shoe shopping guide',
    'Kids shoe clearance',
    "Children's shoe fashion trends",
    'Orthopedic kids shoes',
    "Supportive children's footwear",
    'Orthopedic sandals for kids',
    'Arch support shoes for children',
  ],
  icons: ICONS,
  robots: {
    index: false,
    follow: false,
    nosnippet: false,
    notranslate: false,
    noimageindex: false,
    noarchive: false,
    'max-snippet': -1,
    'max-image-preview': 'standard',
    'max-video-preview': -1,
    googleBot: {
      index: false,
      follow: false,
      nosnippet: false,
      notranslate: false,
      noimageindex: false,
      noarchive: false,
      'max-snippet': -1,
      'max-image-preview': 'standard',
      'max-video-preview': -1,
    },
  },
  openGraph: {
    url: config?.urls.site,
    type: 'website',
    title: 'All products | Weestep - be bigger',
    locale: 'en',
    phoneNumbers: '+34 611-82-25-84',
    siteName: 'Weestep kids',
    alternateLocale: 'en',
    countryName: 'Spain',
    images: {
      url: 'https://img.ankorstore.com/brands/rounded/16969-47df8e2d48b214.jpg?auto=compress&fm=pjpg&h=158&dpr=2',
      width: 200,
      height: 200,
    },
  },
  twitter: {
    site: config?.urls.site,
    card: 'summary_large_image',
    title: 'All products | Weestep - be bigger',
    description: 'Discover a wide selection of stylish and comfortable kids\' shoes at Weestep Kids. Our collection features trendy sneakers, durable sandals, and adorable boots, all crafted with quality materials. From toddler to pre-teen sizes, find the perfect fit for your little one. Shop affordable and on-trend children\'s footwear at Weestep Kids and ensure your child takes every step in style and comfort. Explore our range today!',
    images: {
      url: 'https://img.ankorstore.com/brands/rounded/16969-47df8e2d48b214.jpg?auto=compress&fm=pjpg&h=158&dpr=2',
      width: 200,
      height: 200,
    },
  },
};
